<?php
// This file generated by Propel 1.7.0-dev convert-conf target
// from XML runtime conf file /Users/alex/Projects/rdy4racing-api/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'rdy4racing' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=rdy4racing;port=8889',
        'user' => 'root',
        'password' => 'root',
        'charset' => 
        array (
          'value' => 'utf8',
        ),
        'options' => 
        array (
          'MYSQL_ATTR_INIT_COMMAND' => 
          array (
            'value' => 'SET NAMES utf8 COLLATE utf8_unicode_ci',
          ),
        ),
      ),
    ),
    'prod' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=rdy4racing',
        'user' => 'invalid',
        'password' => 'invalid',
        'charset' => 
        array (
          'value' => 'utf8',
        ),
        'options' => 
        array (
          'MYSQL_ATTR_INIT_COMMAND' => 
          array (
            'value' => 'SET NAMES utf8 COLLATE utf8_unicode_ci',
          ),
        ),
      ),
    ),
    'default' => 'rdy4racing',
  ),
  'generator_version' => '1.7.0-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'rdy4racing-api-classmap.php');
return $conf;