<?php
// This file generated by Propel 1.7.0-dev convert-conf target
// from XML runtime conf file /Users/alex/Projects/rdy4racing-api/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'devel' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=rdy4racing',
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'prod' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=rdy4racing',
        'user' => 'invalid',
        'password' => 'invalid',
      ),
    ),
    'default' => 'devel',
  ),
  'generator_version' => '1.7.0-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'rdy4racing-api-classmap.php');
return $conf;